export const ApiEndpoints = {
  root: '/admin',
  login: '/login',
  forgetPassword: '/forgot-password',
  resetPassword: '/reset-password',
  profile: '/profile',
  editProfile: '/profile-update',
  changePassword: '/change-password',
  verifyOtp: '/verify-otp',
  users: '/users/',
  updateUser: '/users/',
  categories: '/categories',
  addCategory: '/categories',
  deleteCategory: '/categories',
  updateCategory: '/categories',
  contents: '/pages',
  editContent: '/pages/',
  getComission: '/comission',
  updateCommission: '/comission/',
  getFeedbacks: '/feedbacks',
}
